### ISSUE TITLE
Error on elementary OS Loki Beta 2

### ISSUE THREAD

**Issue by bgiesing** [koush/electron-chrome#2] opened 2016-08-29 11:32 UTC
```
bgiesing@bgiesing-Aspire-ZC-700G:~/Documents/electron-chrome-master$ electron . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm
Gtk-Message: Failed to load module "pantheon-filechooser-module"
using chrome runtime 1.0.0.2
chrome app id gidgenkbbabolejbgbpnhbimgjbffefm
{ Error: ENOENT: no such file or directory, scandir '/home/bgiesing/.config/electron-chrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:570:28)
    at getLatestInstalledCrx (/home/bgiesing/Documents/electron-chrome-master/chrome/api/chrome-update.js:144:28)
    at Object.unpackLatestInstalledCrx (/home/bgiesing/Documents/electron-chrome-master/chrome/api/chrome-update.js:153:21)
    at /home/bgiesing/Documents/electron-chrome-master/chrome/main/start.js:37:55
    at Object.<anonymous> (/home/bgiesing/Documents/electron-chrome-master/chrome/main/start.js:140:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/bgiesing/.config/electron-chrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm' }
starting runtime
```

Not sure what the issue is but it opens the Electron Dev console window and that error appears in the terminal.

**Comment by koush** [comment] 2016-08-29 17:38
That's a benign failure message, I'll watch for it. It should continue on and download/open the CRX. Did that work?

**Comment by erraggy** [comment] 2016-08-29 17:43
I get similar for the Hangouts Chrome App:
```
electron . --app-id=knipolnnllmklapflnccelgolnpehhpl
using chrome runtime 1.0.0.2
chrome app id knipolnnllmklapflnccelgolnpehhpl
{ Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:7:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
```
And also end up with the electron dev console:
<img width="798" alt="developer_tools_-_file____users_robbie_projects_electron-chrome_chrome_api_chrome-runtime_html" src="https://cloud.githubusercontent.com/assets/366249/18060905/576bc29a-6dd5-11e6-824e-8d68af618f08.png">

**Comment by erraggy** [comment] 2016-08-29 17:44
After activating the electron dev console window, bash session output these 2 additional lines, but nothing else happens.
```
starting runtime
runtime already exists
```

**Comment by koush** [comment] 2016-08-29 18:19
@erraggy You probably need to "npm install" first.

**Comment by erraggy** [comment] 2016-08-29 18:24
@koush Feeling quite n00bie today, I must admit.

I did the `npm install` from within the root of your repo, and then tried once more and got the same outcome with slightly different error logs:
```
electron . --app-id=knipolnnllmklapflnccelgolnpehhpl
using chrome runtime 1.0.0.2
chrome app id knipolnnllmklapflnccelgolnpehhpl
{ Error: ENOENT: no such file or directory, scandir '/Users/robbie/Library/Application Support/electron-chrome/crx/knipolnnllmklapflnccelgolnpehhpl'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:496:28)
    at getLatestInstalledCrx (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:144:28)
    at Object.unpackLatestInstalledCrx (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:153:21)
    at /Users/robbie/Projects/electron-chrome/chrome/main/start.js:37:55
    at Object.<anonymous> (/Users/robbie/Projects/electron-chrome/chrome/main/start.js:140:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/robbie/Library/Application Support/electron-chrome/crx/knipolnnllmklapflnccelgolnpehhpl' }
starting runtime
runtime already exists
```

Should I be executing this in a different directory or is there something I need in my `$PATH`?

**Comment by koush** [comment] 2016-08-29 18:27
Run with logging please:
electron --enable-logging . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm

**Comment by koush** [comment] 2016-08-29 18:32
Gave it a run myself, it's failing due to missing chrome.i18n

**Comment by erraggy** [comment] 2016-08-29 18:32
I ran both the `app-id` you stated:
```
robbie in ~/Projects/electron-chrome on master
⚡ electron --enable-logging . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm
using chrome runtime 1.0.0.2
chrome app id gidgenkbbabolejbgbpnhbimgjbffefm
{ Error: ENOENT: no such file or directory, scandir '/Users/robbie/Library/Application Support/electron-chrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:496:28)
    at getLatestInstalledCrx (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:144:28)
    at Object.unpackLatestInstalledCrx (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:153:21)
    at /Users/robbie/Projects/electron-chrome/chrome/main/start.js:37:55
    at Object.<anonymous> (/Users/robbie/Projects/electron-chrome/chrome/main/start.js:140:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/robbie/Library/Application Support/electron-chrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm' }
starting runtime
runtime already exists
[11339:0829/113056:INFO:CONSOLE(38)] "chrome runtime started", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (38)
[11339:0829/113056:INFO:CONSOLE(440)] "Uncaught Error: Cannot find module './electron-notifications'", source: module.js (440)
```

As well as against the Hangouts `app-id` with logging:
```
robbie in ~/Projects/electron-chrome on master
⚡ electron --enable-logging . --app-id=knipolnnllmklapflnccelgolnpehhpl
using chrome runtime 1.0.0.2
chrome app id knipolnnllmklapflnccelgolnpehhpl
{ Error: ENOENT: no such file or directory, scandir '/Users/robbie/Library/Application Support/electron-chrome/crx/knipolnnllmklapflnccelgolnpehhpl'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:496:28)
    at getLatestInstalledCrx (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:144:28)
    at Object.unpackLatestInstalledCrx (/Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js:153:21)
    at /Users/robbie/Projects/electron-chrome/chrome/main/start.js:37:55
    at Object.<anonymous> (/Users/robbie/Projects/electron-chrome/chrome/main/start.js:140:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/robbie/Library/Application Support/electron-chrome/crx/knipolnnllmklapflnccelgolnpehhpl' }
starting runtime
runtime already exists
[11314:0829/112950:INFO:CONSOLE(38)] "chrome runtime started", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (38)
[11314:0829/112950:INFO:CONSOLE(440)] "Uncaught Error: Cannot find module './electron-notifications'", source: module.js (440)
```

And the Electron dev console came up the same.

**Comment by koush** [comment] 2016-08-29 18:45
Oh, mind pulling and checking now?

**Comment by erraggy** [comment] 2016-08-29 18:56
Well after I pulled fresh, I tried again and it stops here:
```
robbie in ~/Projects/electron-chrome on master
⚡ electron --enable-logging . --app-id=knipolnnllmklapflnccelgolnpehhpl
using chrome runtime 1.0.0.3
chrome app id knipolnnllmklapflnccelgolnpehhpl
app not installed, fetching...
```

Then if I activate the electron dev console that was spawned, it logs more:
```
starting runtime
runtime already exists
[11506:0829/115613:INFO:CONSOLE(38)] "chrome runtime started", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (38)
[11506:0829/115613:INFO:CONSOLE(440)] "Uncaught Error: Cannot find module './electron-notifications'", source: module.js (440)
```

**Comment by koush** [comment] 2016-08-29 19:00
@erraggy derp. it would help if those files were actually checked in.

Sorry about that.

https://github.com/koush/electron-chrome/commit/509afb1ba7c154865adb336642e9ea402f23462f

**Comment by koush** [comment] 2016-08-29 19:02
Ok, confirmed it is working on a fresh checkout on my machine.

**Comment by erraggy** [comment] 2016-08-29 19:08
Well, I'm definitely getting closer now that I pulled down your most recent additions, but still fails to load.
```
 electron --enable-logging . --app-id=knipolnnllmklapflnccelgolnpehhpl
using chrome runtime 1.0.0.3
chrome app id knipolnnllmklapflnccelgolnpehhpl
app not installed, fetching...
starting runtime
runtime already exists
[11611:0829/120717:INFO:CONSOLE(38)] "chrome runtime started", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (38)
[11611:0829/120717:INFO:CONSOLE(28)] "https://clients2.google.com/service/update2/crx?prodversion=50.0.2661.102&x=id%3Dknipolnnllmklapflnccelgolnpehhpl%26installsource%3Dondemand%26uc%3D", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js (28)
[11611:0829/120717:INFO:CONSOLE(58)] "fetching crx https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1m1iw28TNxcKiIdANuq_--1LhEoBW1cEDpqgus_f-VHxn_3JecGL-Sdz6tbz2ar-roOfCk9Yy7UP3UhvTb2elxAMZSmuWNbyxd4m1YSqaDHjX0-9eTtR5VsQ/extension_2016_809_1413_3.crx", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js (58)
[11611:0829/120717:INFO:CONSOLE(67)] "writing crx to /Users/robbie/Library/Application Support/electron-chrome/crx/knipolnnllmklapflnccelgolnpehhpl/app-2016.809.1413.3.crx", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js (67)
[11611:0829/120717:INFO:CONSOLE(69)] "done writing", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js (69)
[11611:0829/120717:INFO:CONSOLE(247)] "Uncaught (in promise) TypeError: app.relaunch is not a function", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (247)
```

**Comment by koush** [comment] 2016-08-29 21:02
You on the latest electron? You're missing BrowserWindow.getContentBounds. Older version?

**Comment by koush** [comment] 2016-08-29 21:03
You're also missing app.relaunch which is weird. I'll start dumping the environment version to the log.

**Comment by erraggy** [comment] 2016-08-29 21:23
I had an older version (1.1) installed globally at `/usr/local/lib/node_modules/electron-prebuilt` and tried to update it, but that install failed and destroyed the version I had.

I've been browsing all over electron.atom.io and haven't been able to find how to fresh install it so I have a CLI named `electron` that can be kept up-to-date.

**Comment by erraggy** [comment] 2016-08-29 21:34
Ok, I finally fixed my f-d up environment and have 1.3.4 installed globally. Now I don't get anymore error logs, but I do get 2 electron dev console windows.

Here's the output: 
```
robbie in ~/Projects/electron-chrome on master*
⚡ electron --enable-logging . --app-id=knipolnnllmklapflnccelgolnpehhpl
using chrome runtime 1.0.0.3
chrome app id knipolnnllmklapflnccelgolnpehhpl
starting runtime
[15402:0829/143149:INFO:CONSOLE(38)] "chrome runtime started", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (38)
[15402:0829/143150:INFO:CONSOLE(258)] "initialized", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (258)
[15402:0829/143150:INFO:CONSOLE(64)] "creating window", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-app.js (64)
[15402:0829/143150:INFO:CONSOLE(229)] "opening chrome-extension://knipolnnllmklapflnccelgolnpehhpl/_generated_background_page.html", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (229)
[15402:0829/143150:INFO:CONSOLE(154)] "Uncaught TypeError: _._DumpException is not a function", source: chrome-extension://knipolnnllmklapflnccelgolnpehhpl/scripts/main.js (154)
[15402:0829/143150:INFO:CONSOLE(219)] "background onload", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (219)
[15402:0829/143150:INFO:CONSOLE(187)] "checking for updates to chrome app", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (187)
[15402:0829/143150:INFO:CONSOLE(28)] "https://clients2.google.com/service/update2/crx?prodversion=52.0.2743.82&x=id%3Dknipolnnllmklapflnccelgolnpehhpl%26installsource%3Dondemand%26uc%3D", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-update.js (28)
[15402:0829/143151:INFO:CONSOLE(80)] "latest version of", source: /Users/robbie/Projects/electron-chrome/chrome/api/chrome-runtime.js (80)
[15402:0829/143208:WARNING:CONSOLE(2063)] "'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.", source: chrome-devtools://devtools/bundled/inspector.js (2063)
[15402:0829/143215:WARNING:CONSOLE(2063)] "'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.", source: chrome-devtools://devtools/bundled/inspector.js (2063)
chromeRuntimeWindow shutdown
```

**Comment by koush** [comment] 2016-08-29 22:05
Try the vysor one? The Hangouts one wont work due to missing implementations:

electron --enable-logging . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm

**Comment by erraggy** [comment] 2016-08-29 22:56
And vysor works!

Awesome work! Thanks for working with me today. Hopefully the missing implementations will come together.

**Comment by koush** [comment] 2016-08-29 23:10
@erraggy no problem, thanks for your help as well

**Closed by koush** 2016-08-29 23:10 UTC
